### ISSUE TITLE
blcdsdockerregistry/validate:2.0.0 has many high vulnerabilities

### ISSUE THREAD

**Issue by tyamaguchi-ucla** [uclahs-cds/tool-validate-nf#9]
117 High
55  Medium 
558 Low

For example,

https://hub.docker.com/layers/blcdsdockerregistry/validate/2.0.0/images/sha256-a1fbbf32e230104cafd2439d3a4afc2a20306c1ab4f48d4681144c22f987bf1f?context=repo&tab=vulnerabilities

**Comment by ginakkiim** [comment]
Since updating the base image, vulnerabilities have reduced down to:

0 High
2 Medium
17 Low
